version: '3.1'
services:
    mongodb:
        image: mongo:4.1.2-xenial
        container_name: scrappermongodb
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
          - MONGODB_USER=guest 
          - MONGODB_PASS=guest
        ports:
            - 30123:27017
        